name: Create Release Zip

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Create extension zip
        run: |
          zip -r chip-abantecart.zip . \
            -x "*.git*" "*.DS_Store" ".github/*"

      - name: Upload release asset
        run: |
          gh release upload "${{ github.event.release.tag_name }}" chip-abantecart.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
